import api from './api';

export const PRODUCTS = [
  {
    id: 'gold',
    name: 'Gold ETF',
    category: 'Commodities',
    risk: 'Low',
    riskColor: 'text-emerald-600',
    expectedReturn: '9.0%',
    minInvestment: 100,
    description: 'Digital gold ETF providing safety and inflation protection.',
    recommendedFor: 'First-time & conservative investors',
    icon: 'Gem',
    color: '#f59e0b',
  },
  {
    id: 'nifty50',
    name: 'Nifty 50 ETF',
    category: 'Equity ETF',
    risk: 'Moderate',
    riskColor: 'text-blue-600',
    expectedReturn: '13.5%',
    minInvestment: 500,
    description: 'Tracks top 50 bluechip companies listed on India\'s NSE.',
    recommendedFor: 'Long-term capital growth',
    icon: 'TrendingUp',
    color: '#3b82f6',
  },
  {
    id: 'indexfund',
    name: 'Index Mutual Fund',
    category: 'Mutual Funds',
    risk: 'Moderate',
    riskColor: 'text-indigo-600',
    expectedReturn: '12.0%',
    minInvestment: 250,
    description: 'Professionally managed low-cost index tracking fund.',
    recommendedFor: 'Passive wealth building',
    icon: 'BarChart3',
    color: '#8b5cf6',
  },
  {
    id: 'stocks',
    name: 'Bluechip Equity Stocks',
    category: 'Direct Equity',
    risk: 'High',
    riskColor: 'text-amber-600',
    expectedReturn: '16.5%',
    minInvestment: 500,
    description: 'Direct exposure to high-performing market leaders.',
    recommendedFor: 'Growth-oriented portfolios',
    icon: 'LineChart',
    color: '#0f172a',
  },
  {
    id: 'crypto',
    name: 'Crypto Basket ETF',
    category: 'Digital Assets',
    risk: 'Very High',
    riskColor: 'text-rose-600',
    expectedReturn: '24.0%',
    minInvestment: 200,
    description: 'Diversified basket of leading decentralized digital assets.',
    recommendedFor: 'High-risk reward seekers',
    icon: 'Bitcoin',
    color: '#f97316',
  },
  {
    id: 'fd',
    name: 'Fixed Deposit (FD)',
    category: 'Fixed Income',
    risk: 'Very Low',
    riskColor: 'text-teal-600',
    expectedReturn: '7.5%',
    minInvestment: 1000,
    description: 'Guaranteed fixed interest backed by scheduled banks.',
    recommendedFor: 'Capital preservation',
    icon: 'Landmark',
    color: '#0d9488',
  },
];

export const investmentService = {
  getInvestments: async () => api.get('/investments'),
  createInvestment: async ({ productId, investmentType, amount, riskLevel }) =>
    api.post('/investments', { productId: productId || investmentType, amount, riskLevel }),
  addMoney: async ({ amount }) => api.post('/investments/add-money', { amount }),
  getHistory: async () => api.get('/investments/history'),
  getPortfolio: async () => api.get('/investments/portfolio'),
};

export default investmentService;
